import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { readFileSync } from 'node:fs';
import { doc, getDoc, getDocs, setDoc, updateDoc, addDoc, collection, query, where, orderBy, deleteDoc, deleteField, increment, serverTimestamp, writeBatch } from 'firebase/firestore';
// PHASE=2 이면 students 읽기 잠금(2단계) 규칙으로 바꿔서 테스트한다.
const PHASE = process.env.PHASE === '2' ? 2 : 1;
let rulesText = readFileSync(new URL('../ohweb-firestore.rules', import.meta.url), 'utf8');
if (PHASE === 2) rulesText = rulesText.replace(/allow read: if true; \/\/ PHASE2: (allow read: if [^;]+;)/, '$1');
console.log(`[규칙 ${PHASE}단계]`);
const env = await initializeTestEnvironment({ projectId: 'ohweb-93062', firestore: { rules: rulesText, host: '127.0.0.1', port: 8181 } });
await env.clearFirestore();
await env.withSecurityRulesDisabled(async c => {
  const db = c.firestore();
  await setDoc(doc(db, 'students/StuA'), { name: '김학생', schoolName: 'S', grade: '1', class: '2', number: 3, registered: true, failedAttempts: 2 });
  await setDoc(doc(db, 'students/StuB'), { name: '박학생', schoolName: 'S', grade: '1', class: '2', number: 4, registered: false });
  await setDoc(doc(db, 'students/StuL'), { name: '레거시', registered: true, password: 'plain1234' });
  await setDoc(doc(db, 'student_directory/StuA'), { schoolName: 'S', grade: '1', class: '2', number: 3, registered: true, locked: false, failedAttempts: 2 });
  await setDoc(doc(db, 'student_directory/StuB'), { schoolName: 'S', grade: '1', class: '2', number: 4, registered: false, locked: false, failedAttempts: 0 });
  await setDoc(doc(db, 'student_directory/StuC'), { schoolName: 'S', grade: '1', class: '2', number: 5, registered: true, locked: true, failedAttempts: 5 });
  await setDoc(doc(db, 'qna_threads/StuA'), { studentName: '김학생' });
  await setDoc(doc(db, 'posts/p1'), { subKo: 'hi', studentId: 'StuA', name: '김학생', likes: 0, commentCount: 1, classTitle: 'C', pinned: false });
  await setDoc(doc(db, 'posts/p1/comments/c1'), { studentId: 'StuA', name: '김학생', text: '댓글' });
  await setDoc(doc(db, 'students/Master'), { name: '선생님', isMaster: true, registered: true });
  await setDoc(doc(db, 'student_forms/F1'), { ownerId: 'StuA', title: '설문', status: 'open', responseCount: 1, questions: [] });
  await setDoc(doc(db, 'student_form_responses/R1'), { formId: 'F1', ownerId: 'StuA', respondentId: 'StuB', respondentName: '4 박학생', answers: ['비밀 답'] });
  await setDoc(doc(db, 'student_form_responses/R2'), { formId: 'F1', ownerId: 'StuA', respondentId: 'anonymous', respondentName: '익명', answers: ['x'] });
  await setDoc(doc(db, 'qna_threads/StuA/messages/m1'), { text: '비밀 상담', sender: 'student' });
  await setDoc(doc(db, 'exam_progress/AS1_StuA'), { studentId: 'StuA', name: '김학생', status: 'started', alertCount: 1 });
  await setDoc(doc(db, 'exam_progress/AS2_StuA'), { studentId: 'StuA', name: '김학생', totalScore: 40, status: 'submitted' });
  await setDoc(doc(db, 'exam_results/AS2_StuA_0'), { asId: 'AS2', studentId: 'StuA', score: 10 });
  await setDoc(doc(db, 'exam_results/AS2_StuB_0'), { asId: 'AS2', studentId: 'StuB', score: 5 });
});
const anon = env.unauthenticatedContext().firestore();
const A = env.authenticatedContext('uidA', { email: 'stua@ohinfo.local', email_verified: false }).firestore();
const B = env.authenticatedContext('uidB', { email: 'stub@ohinfo.local' }).firestore();
const L = env.authenticatedContext('uidL', { email: 'stul@ohinfo.local' }).firestore();
const admin = env.authenticatedContext('adm', { email: 'qjatjr7575@gmail.com', email_verified: true }).firestore();
const fakeAdmin = env.authenticatedContext('fake', { email: 'qjatjr7575@gmail.com', email_verified: false }).firestore();
let fails = 0;
const T = async (label, p, expectOk) => { try { await p; if (!expectOk) { fails++; console.log('❌ 뚫림  ' + label); } else console.log('✅ 허용  ' + label); } catch (e) { if (expectOk) { fails++; console.log('❌ 막힘  ' + label + ' — ' + e.code); } else console.log('✅ 차단  ' + label); } };
console.log('── 공격 ──');
await T('학생 본인이 isMaster:true 셀프 부여', updateDoc(doc(A, 'students/StuA'), { isMaster: true }), false);
await T('학생 본인이 이름 변경', updateDoc(doc(A, 'students/StuA'), { name: 'x' }), false);
await T('학생 본인이 registered를 false로', updateDoc(doc(A, 'students/StuA'), { registered: false }), false);
await T('비로그인이 isMaster 학생 문서 생성', setDoc(doc(anon, 'students/Evil'), { name: 'x', isMaster: true }), false);
await T('로그인 학생이 학생 문서 생성', setDoc(doc(A, 'students/Evil2'), { name: 'x' }), false);
await T('비로그인이 남의 1:1 질문 읽기', getDocs(collection(anon, 'qna_threads/StuA/messages')), false);
await T('다른 학생이 남의 1:1 질문 읽기', getDocs(collection(B, 'qna_threads/StuA/messages')), false);
await T('다른 학생이 남의 스레드에 메시지 쓰기', addDoc(collection(B, 'qna_threads/StuA/messages'), { text: 'x' }), false);
await T('관리자가 전체 스레드 목록(비로그인)', getDocs(collection(anon, 'qna_threads')), false);
await T('비로그인이 시험 점수 읽기', getDoc(doc(anon, 'exam_progress/AS2_StuA')), false);
await T('다른 학생이 남의 시험 진행 읽기', getDoc(doc(B, 'exam_progress/AS2_StuA')), false);
await T('다른 학생이 남의 진행 기록 쓰기', setDoc(doc(B, 'exam_progress/AS1_StuA'), { alertCount: 0 }, { merge: true }), false);
await T('학생이 남의 ID로 진행 기록 생성', setDoc(doc(B, 'exam_progress/AS9_StuA'), { studentId: 'StuA' }), false);
await T('학생이 진행 기록 studentId 바꿔치기', setDoc(doc(A, 'exam_progress/AS1_StuA'), { studentId: 'StuB' }, { merge: true }), false);
await T('학생이 제출 후 점수 수정', setDoc(doc(A, 'exam_progress/AS2_StuA'), { totalScore: 100 }, { merge: true }), false);
await T('학생이 이탈 횟수 0으로 되돌리기(제출 후)', setDoc(doc(A, 'exam_progress/AS2_StuA'), { alertCount: 0 }, { merge: true }), false);
await T('학생이 남의 채점 결과 조회', getDocs(query(collection(B, 'exam_results'), where('asId', '==', 'AS2'), where('studentId', '==', 'StuA'))), false);
await T('email_verified 없는 가짜 관리자', getDocs(collection(fakeAdmin, 'qna_threads')), false);
await T('비로그인 잠금 해제 시도', updateDoc(doc(anon, 'students/StuA'), { failedAttempts: 0 }), false);
await T('명단: 비로그인 잠금 해제', updateDoc(doc(anon, 'student_directory/StuC'), { locked: false }), false);
await T('명단: 비로그인 실패 카운트 0으로', updateDoc(doc(anon, 'student_directory/StuA'), { failedAttempts: 0 }), false);
await T('명단: 비로그인이 가입 표시 조작', updateDoc(doc(anon, 'student_directory/StuB'), { registered: true }), false);
const Cc = env.authenticatedContext('uidC', { email: 'stuc@ohinfo.local' }).firestore();
await T('명단: 잠긴 본인이 자기 잠금 해제', updateDoc(doc(Cc, 'student_directory/StuC'), { locked: false }), false);
await T('명단: 다른 학생이 남의 가입 표시', updateDoc(doc(A, 'student_directory/StuB'), { registered: true }), false);
await T('명단: 비로그인이 항목 생성', setDoc(doc(anon, 'student_directory/X'), { schoolName: 'S' }), false);
await T('명단: 학생이 항목 삭제', deleteDoc(doc(A, 'student_directory/StuA')), false);
await T('게시판: 비로그인이 게시글 읽기', getDocs(collection(anon, 'posts')), false);
await T('게시판: 남의 글 내용 수정', updateDoc(doc(B, 'posts/p1'), { subKo: 'hacked' }), false);
await T('게시판: 남의 글 삭제 표시', updateDoc(doc(B, 'posts/p1'), { deleted: true }), false);
await T('게시판: 남의 글 실제 삭제', deleteDoc(doc(B, 'posts/p1')), false);
await T('게시판: 남 이름으로 글쓰기', addDoc(collection(B, 'posts'), { studentId: 'StuA', subKo: 'x' }), false);
await T('게시판: 좋아요 수 조작(+100)', updateDoc(doc(B, 'posts/p1'), { likes: 100 }), false);
await T('게시판: 좋아요에 끼워서 내용 수정', updateDoc(doc(B, 'posts/p1'), { likes: increment(1), subKo: 'x' }), false);
await T('게시판: 일반 학생이 고정', updateDoc(doc(B, 'posts/p1'), { pinned: true, pinnedBy: 'StuB' }), false);
await T('게시판: 마스터 사칭 고정(남의 ID)', updateDoc(doc(B, 'posts/p1'), { pinned: true, pinnedBy: 'Master' }), false);
await T('게시판: 남 이름으로 댓글', addDoc(collection(B, 'posts/p1/comments'), { studentId: 'StuA', text: 'x' }), false);
await T('게시판: 남의 댓글 삭제', deleteDoc(doc(B, 'posts/p1/comments/c1')), false);
await T('설문: 비로그인이 응답 전체 읽기', getDocs(collection(anon, 'student_form_responses')), false);
await T('설문: 다른 학생이 남의 설문 응답 읽기', getDocs(query(collection(L, 'student_form_responses'), where('formId', '==', 'F1'))), false);
await T('설문: 응답자가 같은 설문의 남 응답까지 읽기', getDocs(query(collection(B, 'student_form_responses'), where('formId', '==', 'F1'))), false);
await T('설문: 남의 이름으로 응답 제출', addDoc(collection(B, 'student_form_responses'), { formId: 'F1', ownerId: 'StuA', respondentId: 'StuA', answers: [] }), false);
await T('설문: 남의 설문 수정', updateDoc(doc(B, 'student_forms/F1'), { title: 'hacked' }), false);
await T('설문: 남의 설문 삭제', deleteDoc(doc(B, 'student_forms/F1')), false);
await T('설문: 남 이름으로 설문 생성', setDoc(doc(B, 'student_forms/F9'), { ownerId: 'StuA', title: 'x' }), false);
await T('설문: 응답 수 크게 조작', updateDoc(doc(anon, 'student_forms/F1'), { responseCount: 999 }), false);
await T('설문: 소유자 바꿔치기', updateDoc(doc(A, 'student_forms/F1'), { ownerId: 'StuB' }), false);
await T('설문: 남의 응답 삭제', deleteDoc(doc(B, 'student_form_responses/R2')), false);
if (PHASE === 2) {
  await T('[2단계] 비로그인이 학생 명단(이름·사진) 읽기', getDocs(collection(anon, 'students')), false);
  await T('[2단계] 다른 학생 문서 읽기', getDoc(doc(B, 'students/StuA')), false);
  await T('[2단계] 로그인 학생이 명단 전체 읽기', getDocs(collection(A, 'students')), false);
}
console.log('── 정상 기능 ──');
if (PHASE === 1) await T('[1단계] 로그인 화면 대체 경로: 비로그인 students 조회', getDocs(collection(anon, 'students')), true);
await T('로그인 화면: 비로그인 공개 명단 조회', getDocs(collection(anon, 'student_directory')), true);
await T('명단: 로그인 실패 카운트 증가(비로그인)', updateDoc(doc(anon, 'student_directory/StuB'), { failedAttempts: increment(1) }), true);
await T('명단: 5회 실패 잠금(비로그인)', updateDoc(doc(anon, 'student_directory/StuB'), { failedAttempts: increment(1), locked: true, lockedAt: serverTimestamp() }), true);
await env.withSecurityRulesDisabled(async c => { await updateDoc(doc(c.firestore(), 'student_directory/StuB'), { locked: false, failedAttempts: 0 }); });
await T('명단: 로그인 성공 후 카운트 0 리셋(본인)', updateDoc(doc(A, 'student_directory/StuA'), { failedAttempts: 0 }), true);
await T('명단: 가입 표시(본인)', updateDoc(doc(B, 'student_directory/StuB'), { registered: true }), true);
await T('가입 직후 본인 문서 읽기(이름 대조)', getDoc(doc(B, 'students/StuB')), true);
await T('관리자: 명단 동기화(생성/수정/삭제/잠금해제)', (async () => { const b = writeBatch(admin); b.set(doc(admin, 'student_directory/New1'), { schoolName: 'S', registered: false, locked: false, failedAttempts: 0 }); b.update(doc(admin, 'student_directory/StuA'), { grade: '2' }); b.delete(doc(admin, 'student_directory/StuB')); await b.commit(); await setDoc(doc(admin, 'student_directory/StuC'), { locked: false, failedAttempts: 0 }, { merge: true }); await getDocs(collection(admin, 'student_directory')); })(), true);
await T('로그인 실패 카운트 증가(비로그인)', updateDoc(doc(anon, 'students/StuA'), { failedAttempts: increment(1) }), true);
await T('5회 실패 잠금(비로그인)', updateDoc(doc(anon, 'students/StuB'), { failedAttempts: increment(1), locked: true, lockedAt: serverTimestamp() }), true);
await T('로그인 성공 후 카운트 0 리셋(본인)', updateDoc(doc(A, 'students/StuA'), { failedAttempts: 0 }), true);
await T('레거시 전환: password 삭제 + 0 리셋(본인)', updateDoc(doc(L, 'students/StuL'), { password: deleteField(), failedAttempts: 0 }), true);
await env.withSecurityRulesDisabled(async c => { await updateDoc(doc(c.firestore(), 'students/StuB'), { locked: false, failedAttempts: 0 }); });
await T('가입: registered:true + 사진(본인)', updateDoc(doc(B, 'students/StuB'), { photoUrl: 'data:image/jpeg;base64,AAAA', registered: true }), true);
await T('마이페이지 사진 변경(본인)', updateDoc(doc(A, 'students/StuA'), { photoUrl: 'data:image/jpeg;base64,BBBB' }), true);
await T('세션 확인: 본인 문서 읽기', getDoc(doc(A, 'students/StuA')), true);
await T('1:1 질문: 본인 스레드 읽기', getDoc(doc(A, 'qna_threads/StuA')), true);
await T('1:1 질문: 본인 메시지 목록(orderBy)', getDocs(query(collection(A, 'qna_threads/StuA/messages'), orderBy('createdAt', 'asc'))), true);
await T('1:1 질문: 본인 메시지 쓰기', addDoc(collection(A, 'qna_threads/StuA/messages'), { sender: 'student', text: 'q', attachments: [], createdAt: serverTimestamp() }), true);
await T('1:1 질문: 본인 스레드 갱신', setDoc(doc(A, 'qna_threads/StuA'), { unreadByAdmin: true }, { merge: true }), true);
await T('1:1 질문: 새 학생 스레드 생성', setDoc(doc(B, 'qna_threads/StuB'), { studentName: '박학생' }), true);
await T('1:1 질문: 선생님 답장 읽음 표시', updateDoc(doc(A, 'qna_threads/StuA/messages/m1'), { readAt: serverTimestamp() }), true);
await T('시험 목록: 본인 진행 기록(없는 문서) 읽기', getDoc(doc(A, 'exam_progress/AS7_StuA')), true);
await T('시험 목록: 본인 진행 기록 읽기', getDoc(doc(A, 'exam_progress/AS2_StuA')), true);
await T('시험 입장: 진행 기록 생성(merge)', setDoc(doc(B, 'exam_progress/AS1_StuB'), { examId: 'E', asId: 'AS1', studentId: 'StuB', name: '박', status: 'started', alertCount: 0, pasteBlockCount: 0, startTime: serverTimestamp() }, { merge: true }), true);
await T('시험 중: 이탈 횟수 갱신', setDoc(doc(A, 'exam_progress/AS1_StuA'), { alertCount: 2 }, { merge: true }), true);
await T('시험 중: 붙여넣기 횟수 갱신', setDoc(doc(A, 'exam_progress/AS1_StuA'), { pasteBlockCount: 1 }, { merge: true }), true);
await T('제출 실패: 답안 보관', setDoc(doc(A, 'exam_progress/AS1_StuA'), { pendingAnswers: [{ qIdx: 0, value: '1' }], pendingAt: serverTimestamp(), submitError: 'x' }, { merge: true }), true);
await T('결과 보기: 본인 채점 결과 조회', getDocs(query(collection(A, 'exam_results'), where('asId', '==', 'AS2'), where('studentId', '==', 'StuA'))), true);
const M = env.authenticatedContext('uidM', { email: 'master@ohinfo.local' }).firestore();
await T('게시판: 학생이 수업 게시글 읽기', getDocs(query(collection(B, 'posts'), where('classTitle', '==', 'C'))), true);
await T('게시판: 증분 동기화 쿼리(updatedAt >)', getDocs(query(collection(B, 'posts'), where('classTitle', '==', 'C'), where('updatedAt', '>', new Date(0)))), true);
await T('게시판: 글쓰기(본인)', addDoc(collection(B, 'posts'), { classTitle: 'C', studentId: 'StuB', name: '박', subKo: 's', imgs: [], likes: 0, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }), true);
await T('게시판: 내 글 수정', updateDoc(doc(A, 'posts/p1'), { subKo: '수정', imgs: [], updatedAt: serverTimestamp() }), true);
await T('게시판: 좋아요 +1 / -1', (async () => { await updateDoc(doc(B, 'posts/p1'), { likes: increment(1), updatedAt: serverTimestamp() }); await updateDoc(doc(B, 'posts/p1'), { likes: increment(-1), updatedAt: serverTimestamp() }); })(), true);
await T('게시판: 댓글 읽기·달기 + 댓글 수 +1', (async () => { await getDocs(query(collection(B, 'posts/p1/comments'), orderBy('createdAt', 'asc'))); await addDoc(collection(B, 'posts/p1/comments'), { studentId: 'StuB', name: '박', num: '4', text: 'hi', createdAt: serverTimestamp() }); await updateDoc(doc(B, 'posts/p1'), { commentCount: increment(1), updatedAt: serverTimestamp() }); })(), true);
await T('게시판: 내 댓글 삭제 + 댓글 수 -1', (async () => { await deleteDoc(doc(A, 'posts/p1/comments/c1')); await updateDoc(doc(A, 'posts/p1'), { commentCount: increment(-1), updatedAt: serverTimestamp() }); })(), true);
await T('게시판: 마스터 고정', updateDoc(doc(M, 'posts/p1'), { pinned: true, pinnedBy: 'Master', updatedAt: serverTimestamp() }), true);
await T('게시판: 내 글 삭제 표시', updateDoc(doc(A, 'posts/p1'), { deleted: true, updatedAt: serverTimestamp() }), true);
await T('게시판(admin): 게시글 조회·번역 저장', (async () => { await getDocs(query(collection(admin, 'posts'), where('classTitle', '==', 'C'))); await updateDoc(doc(admin, 'posts/p1'), { subEn: 'hi' }); })(), true);
await T('설문(formfill): 설문 열기(비로그인)', getDoc(doc(anon, 'student_forms/F1')), true);
await T('설문(formfill): 1회 제한 확인 — 내 응답 조회', getDocs(query(collection(B, 'student_form_responses'), where('formId', '==', 'F1'), where('respondentId', '==', 'StuB'))), true);
await T('설문(formfill): 로그인 응답 제출', addDoc(collection(B, 'student_form_responses'), { formId: 'F1', ownerId: 'StuA', respondentId: 'StuB', respondentName: '4 박', answers: [], submittedAt: serverTimestamp() }), true);
await T('설문(formfill): 비로그인 익명 응답 제출', addDoc(collection(anon, 'student_form_responses'), { formId: 'F1', ownerId: 'StuA', respondentId: 'anonymous', respondentName: '익명', answers: [] }), true);
await T('설문(formfill): 응답 수 +1(비로그인)', updateDoc(doc(anon, 'student_forms/F1'), { responseCount: increment(1) }), true);
await T('설문(formlab): 내 설문 목록', getDocs(query(collection(A, 'student_forms'), where('ownerId', '==', 'StuA'))), true);
await T('설문(formlab): 내 설문 응답 조회', getDocs(query(collection(A, 'student_form_responses'), where('formId', '==', 'F1'), where('ownerId', '==', 'StuA'))), true);
await T('설문(formlab): 새 설문 만들기', addDoc(collection(A, 'student_forms'), { ownerId: 'StuA', title: 't', status: 'open', responseCount: 0 }), true);
await T('설문(formlab): 설문 수정·마감', updateDoc(doc(A, 'student_forms/F1'), { title: '수정', status: 'closed' }), true);
await T('설문(formlab): 응답 1건 삭제 + 응답 수 -1', (async () => { await deleteDoc(doc(A, 'student_form_responses/R2')); await updateDoc(doc(A, 'student_forms/F1'), { responseCount: increment(-1) }); })(), true);
await T('설문(admin): 전체 설문·응답 조회, 마감, 삭제', (async () => { await getDocs(collection(admin, 'student_forms')); await getDocs(collection(admin, 'student_form_responses')); await updateDoc(doc(admin, 'student_forms/F1'), { status: 'open' }); await deleteDoc(doc(admin, 'student_form_responses/R1')); })(), true);
await T('설문(formlab): 설문 삭제', deleteDoc(doc(A, 'student_forms/F1')), true);
await T('관리자: 학생 목록/수정/잠금해제', (async () => { await getDocs(collection(admin, 'students')); await updateDoc(doc(admin, 'students/StuA'), { name: '김', isMaster: true, locked: false, failedAttempts: 0 }); })(), true);
await T('관리자: 학생 생성/삭제', (async () => { await addDoc(collection(admin, 'students'), { name: 'n' }); await deleteDoc(doc(admin, 'students/StuL')); })(), true);
await T('관리자: 스레드 목록·답장', (async () => { await getDocs(collection(admin, 'qna_threads')); await addDoc(collection(admin, 'qna_threads/StuA/messages'), { sender: 'admin', text: 'a' }); await updateDoc(doc(admin, 'qna_threads/StuA'), { unreadByStudent: true }); })(), true);
await T('관리자: 시험 결과 목록·채점 저장·보관 답안 반영', (async () => { await getDocs(query(collection(admin, 'exam_progress'), where('asId', '==', 'AS1'))); const b = writeBatch(admin); b.set(doc(admin, 'exam_results/AS1_StuA_0'), { score: 1 }); b.set(doc(admin, 'exam_progress/AS1_StuA'), { status: 'submitted', totalScore: 1, totalPoints: 1 }, { merge: true }); await b.commit(); })(), true);
console.log(fails ? `\n실패 ${fails}건` : '\n전부 통과'); process.exitCode = fails ? 1 : 0;
await env.cleanup();
