import { initializeTestEnvironment } from '@firebase/rules-unit-testing';
import { readFileSync } from 'node:fs';
import { doc, getDoc, getDocs, setDoc, updateDoc, addDoc, collection, query, where, orderBy, deleteDoc, deleteField, increment, serverTimestamp, writeBatch } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'ohweb-93062', firestore: { rules: readFileSync(new URL('../ohweb-firestore.rules', import.meta.url), 'utf8'), host: '127.0.0.1', port: 8181 } });
await env.clearFirestore();
await env.withSecurityRulesDisabled(async c => {
  const db = c.firestore();
  await setDoc(doc(db, 'students/StuA'), { name: '김학생', schoolName: 'S', grade: '1', class: '2', number: 3, registered: true, failedAttempts: 2 });
  await setDoc(doc(db, 'students/StuB'), { name: '박학생', schoolName: 'S', grade: '1', class: '2', number: 4, registered: false });
  await setDoc(doc(db, 'students/StuL'), { name: '레거시', registered: true, password: 'plain1234' });
  await setDoc(doc(db, 'qna_threads/StuA'), { studentName: '김학생' });
  await setDoc(doc(db, 'qna_threads/StuA/messages/m1'), { text: '비밀 상담', sender: 'student' });
  await setDoc(doc(db, 'exam_progress/AS1_StuA'), { studentId: 'StuA', name: '김학생', status: 'started', alertCount: 1 });
  await setDoc(doc(db, 'exam_progress/AS2_StuA'), { studentId: 'StuA', name: '김학생', totalScore: 40, status: 'submitted' });
  await setDoc(doc(db, 'exam_results/AS2_StuA_0'), { asId: 'AS2', studentId: 'StuA', score: 10 });
  await setDoc(doc(db, 'exam_results/AS2_StuB_0'), { asId: 'AS2', studentId: 'StuB', score: 5 });
});
const anon = env.unauthenticatedContext().firestore();
const A = env.authenticatedContext('uidA', { email: 'stua@ohinfo.local', email_verified: false }).firestore();
const B = env.authenticatedContext('uidB', { email: 'stub@ohinfo.local' }).firestore();
const L = env.authenticatedContext('uidL', { email: 'stul@ohinfo.local' }).firestore();
const admin = env.authenticatedContext('adm', { email: 'qjatjr7575@gmail.com', email_verified: true }).firestore();
const fakeAdmin = env.authenticatedContext('fake', { email: 'qjatjr7575@gmail.com', email_verified: false }).firestore();
let fails = 0;
const T = async (label, p, expectOk) => { try { await p; if (!expectOk) { fails++; console.log('❌ 뚫림  ' + label); } else console.log('✅ 허용  ' + label); } catch (e) { if (expectOk) { fails++; console.log('❌ 막힘  ' + label + ' — ' + e.code); } else console.log('✅ 차단  ' + label); } };
console.log('── 공격 ──');
await T('학생 본인이 isMaster:true 셀프 부여', updateDoc(doc(A, 'students/StuA'), { isMaster: true }), false);
await T('학생 본인이 이름 변경', updateDoc(doc(A, 'students/StuA'), { name: 'x' }), false);
await T('학생 본인이 registered를 false로', updateDoc(doc(A, 'students/StuA'), { registered: false }), false);
await T('비로그인이 isMaster 학생 문서 생성', setDoc(doc(anon, 'students/Evil'), { name: 'x', isMaster: true }), false);
await T('로그인 학생이 학생 문서 생성', setDoc(doc(A, 'students/Evil2'), { name: 'x' }), false);
await T('비로그인이 남의 1:1 질문 읽기', getDocs(collection(anon, 'qna_threads/StuA/messages')), false);
await T('다른 학생이 남의 1:1 질문 읽기', getDocs(collection(B, 'qna_threads/StuA/messages')), false);
await T('다른 학생이 남의 스레드에 메시지 쓰기', addDoc(collection(B, 'qna_threads/StuA/messages'), { text: 'x' }), false);
await T('관리자가 전체 스레드 목록(비로그인)', getDocs(collection(anon, 'qna_threads')), false);
await T('비로그인이 시험 점수 읽기', getDoc(doc(anon, 'exam_progress/AS2_StuA')), false);
await T('다른 학생이 남의 시험 진행 읽기', getDoc(doc(B, 'exam_progress/AS2_StuA')), false);
await T('다른 학생이 남의 진행 기록 쓰기', setDoc(doc(B, 'exam_progress/AS1_StuA'), { alertCount: 0 }, { merge: true }), false);
await T('학생이 남의 ID로 진행 기록 생성', setDoc(doc(B, 'exam_progress/AS9_StuA'), { studentId: 'StuA' }), false);
await T('학생이 진행 기록 studentId 바꿔치기', setDoc(doc(A, 'exam_progress/AS1_StuA'), { studentId: 'StuB' }, { merge: true }), false);
await T('학생이 제출 후 점수 수정', setDoc(doc(A, 'exam_progress/AS2_StuA'), { totalScore: 100 }, { merge: true }), false);
await T('학생이 이탈 횟수 0으로 되돌리기(제출 후)', setDoc(doc(A, 'exam_progress/AS2_StuA'), { alertCount: 0 }, { merge: true }), false);
await T('학생이 남의 채점 결과 조회', getDocs(query(collection(B, 'exam_results'), where('asId', '==', 'AS2'), where('studentId', '==', 'StuA'))), false);
await T('email_verified 없는 가짜 관리자', getDocs(collection(fakeAdmin, 'qna_threads')), false);
await T('비로그인 잠금 해제 시도', updateDoc(doc(anon, 'students/StuA'), { failedAttempts: 0 }), false);
console.log('── 정상 기능 ──');
await T('로그인 화면: 비로그인 학생 목록 조회(아직 공개, P0-4에서 처리)', getDocs(collection(anon, 'students')), true);
await T('로그인 실패 카운트 증가(비로그인)', updateDoc(doc(anon, 'students/StuA'), { failedAttempts: increment(1) }), true);
await T('5회 실패 잠금(비로그인)', updateDoc(doc(anon, 'students/StuB'), { failedAttempts: increment(1), locked: true, lockedAt: serverTimestamp() }), true);
await T('로그인 성공 후 카운트 0 리셋(본인)', updateDoc(doc(A, 'students/StuA'), { failedAttempts: 0 }), true);
await T('레거시 전환: password 삭제 + 0 리셋(본인)', updateDoc(doc(L, 'students/StuL'), { password: deleteField(), failedAttempts: 0 }), true);
await env.withSecurityRulesDisabled(async c => { await updateDoc(doc(c.firestore(), 'students/StuB'), { locked: false, failedAttempts: 0 }); });
await T('가입: registered:true + 사진(본인)', updateDoc(doc(B, 'students/StuB'), { photoUrl: 'data:image/jpeg;base64,AAAA', registered: true }), true);
await T('마이페이지 사진 변경(본인)', updateDoc(doc(A, 'students/StuA'), { photoUrl: 'data:image/jpeg;base64,BBBB' }), true);
await T('세션 확인: 본인 문서 읽기', getDoc(doc(A, 'students/StuA')), true);
await T('1:1 질문: 본인 스레드 읽기', getDoc(doc(A, 'qna_threads/StuA')), true);
await T('1:1 질문: 본인 메시지 목록(orderBy)', getDocs(query(collection(A, 'qna_threads/StuA/messages'), orderBy('createdAt', 'asc'))), true);
await T('1:1 질문: 본인 메시지 쓰기', addDoc(collection(A, 'qna_threads/StuA/messages'), { sender: 'student', text: 'q', attachments: [], createdAt: serverTimestamp() }), true);
await T('1:1 질문: 본인 스레드 갱신', setDoc(doc(A, 'qna_threads/StuA'), { unreadByAdmin: true }, { merge: true }), true);
await T('1:1 질문: 새 학생 스레드 생성', setDoc(doc(B, 'qna_threads/StuB'), { studentName: '박학생' }), true);
await T('1:1 질문: 선생님 답장 읽음 표시', updateDoc(doc(A, 'qna_threads/StuA/messages/m1'), { readAt: serverTimestamp() }), true);
await T('시험 목록: 본인 진행 기록(없는 문서) 읽기', getDoc(doc(A, 'exam_progress/AS7_StuA')), true);
await T('시험 목록: 본인 진행 기록 읽기', getDoc(doc(A, 'exam_progress/AS2_StuA')), true);
await T('시험 입장: 진행 기록 생성(merge)', setDoc(doc(B, 'exam_progress/AS1_StuB'), { examId: 'E', asId: 'AS1', studentId: 'StuB', name: '박', status: 'started', alertCount: 0, pasteBlockCount: 0, startTime: serverTimestamp() }, { merge: true }), true);
await T('시험 중: 이탈 횟수 갱신', setDoc(doc(A, 'exam_progress/AS1_StuA'), { alertCount: 2 }, { merge: true }), true);
await T('시험 중: 붙여넣기 횟수 갱신', setDoc(doc(A, 'exam_progress/AS1_StuA'), { pasteBlockCount: 1 }, { merge: true }), true);
await T('제출 실패: 답안 보관', setDoc(doc(A, 'exam_progress/AS1_StuA'), { pendingAnswers: [{ qIdx: 0, value: '1' }], pendingAt: serverTimestamp(), submitError: 'x' }, { merge: true }), true);
await T('결과 보기: 본인 채점 결과 조회', getDocs(query(collection(A, 'exam_results'), where('asId', '==', 'AS2'), where('studentId', '==', 'StuA'))), true);
await T('관리자: 학생 목록/수정/잠금해제', (async () => { await getDocs(collection(admin, 'students')); await updateDoc(doc(admin, 'students/StuA'), { name: '김', isMaster: true, locked: false, failedAttempts: 0 }); })(), true);
await T('관리자: 학생 생성/삭제', (async () => { await addDoc(collection(admin, 'students'), { name: 'n' }); await deleteDoc(doc(admin, 'students/StuL')); })(), true);
await T('관리자: 스레드 목록·답장', (async () => { await getDocs(collection(admin, 'qna_threads')); await addDoc(collection(admin, 'qna_threads/StuA/messages'), { sender: 'admin', text: 'a' }); await updateDoc(doc(admin, 'qna_threads/StuA'), { unreadByStudent: true }); })(), true);
await T('관리자: 시험 결과 목록·채점 저장·보관 답안 반영', (async () => { await getDocs(query(collection(admin, 'exam_progress'), where('asId', '==', 'AS1'))); const b = writeBatch(admin); b.set(doc(admin, 'exam_results/AS1_StuA_0'), { score: 1 }); b.set(doc(admin, 'exam_progress/AS1_StuA'), { status: 'submitted', totalScore: 1, totalPoints: 1 }, { merge: true }); await b.commit(); })(), true);
console.log(fails ? `\n실패 ${fails}건` : '\n전부 통과'); process.exitCode = fails ? 1 : 0;
await env.cleanup();
